# Generated by Django 5.0.6 on 2024-09-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('vaccine_campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('next_vaccine_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user.useraccount')),
                ('vaccine_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_campaign', to='vaccine_campaign.vaccinecampaign')),
            ],
        ),
    ]
