# Generated by Django 5.0.6 on 2024-09-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('vaccine_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinebooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user.useraccount'),
        ),
    ]
