# Generated by Django 5.0.6 on 2024-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_booking', '0003_alter_vaccinebooking_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinebooking',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
