# Generated by Django 5.0.6 on 2024-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_booking', '0004_vaccinebooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinebooking',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
