# Generated by Django 5.0.6 on 2024-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecampaign',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
