# Generated by Django 5.0.6 on 2024-09-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_useraccount_balance_and_more'),
        ('vaccine_campaign', '0002_vaccinecampaign_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCampaignReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reviews', to='user.useraccount')),
                ('vaccine_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_reviews', to='vaccine_campaign.vaccinecampaign')),
            ],
        ),
    ]
