# Generated by Django 5.0.6 on 2024-09-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='initial_deposite_date',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='nid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
